version: '3'
services:
    mysqlserver:
        image: mysql:8.0.23
        container_name: mysql
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - MYSQL_USER=root
            - MYSQL_PASSWORD=pankaj
            - MYSQL_DATABASE=college

    college-management-system:
        # in case you wont to run the project from docker hub uncomment the next line and commet the next two lines
        # image: krishnadockeraccount/college-management-system:latest
        build:
            context: .
        ports:
            - 8000:8000
            - 8080:8080
        environment:
            - SERVER_PORT=8080
            - spring.datasource.url=jdbc:mysql://mysqlserver:3306/college?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
            - spring.datasource.username=root
            - spring.datasource.password=
        volumes:
            - ./:/app
        command: ./mvnw spring-boot:run 
         ## -Dspring-boot.run.profiles=local
    
